{
    "name": "Islamic Educational Complex",
    "summary": "Manage students, teachers, levels, scheduling, attendance, evaluations, and fees",
    "version": "19.0.1.0.0",
    "category": "Education",
    "author": "Codex CLI",
    "license": "LGPL-3",
    "application": True,
    "depends": ["base", "hr", "mail", "account"],
    "data": [
        "security/edu_groups.xml",
        "security/ir.model.access.csv",
        "security/edu_rules.xml",
        "data/sequence.xml",
        "views/menus.xml",
        "views/student_views.xml",
        "views/guardian_views.xml",
        "views/level_views.xml",
        "views/class_group_views.xml",
        "views/enrollment_views.xml",
        "views/assignment_views.xml",
        "views/session_views.xml",
        "views/attendance_views.xml",
        "views/evaluation_views.xml",
        "views/fees_views.xml",
        "views/hr_employee_views.xml",
        "views/dashboard_views.xml",
        "views/settings_views.xml",
        "views/wizard_views.xml",
    ],
    "demo": ["data/demo.xml"],
    "installable": True,
}
